// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Contents: typeof import('./src/components/Contents.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IRiArrowRightLine: typeof import('~icons/ri/arrow-right-line')['default']
    IRiDownloadLine: typeof import('~icons/ri/download-line')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    IRiGithubFill: typeof import('~icons/ri/github-fill')['default']
  }
}
